name: Deploy Next.js full app to Azure Web App - FeedXchangeOnNodeJS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Upload source code (excluding node_modules and .next)
        uses: actions/upload-artifact@v4
        with:
          name: app-code
          path: |
            ./
            !node_modules/**
            !.next/**

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: app-code

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FeedXchangeOnNodeJS'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0C47C12011AE4AD1850F468D13DC1B5E }}
          package: .
